// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: inventory.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_PurchaseInventoryProduct_FullMethodName = "/InventoryService/PurchaseInventoryProduct"
	InventoryService_SupplyInventoryProduct_FullMethodName   = "/InventoryService/SupplyInventoryProduct"
	InventoryService_CorrectInventoryStock_FullMethodName    = "/InventoryService/CorrectInventoryStock"
	InventoryService_ListStockMovements_FullMethodName       = "/InventoryService/ListStockMovements"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	PurchaseInventoryProduct(ctx context.Context, in *PurchaseInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error)
	SupplyInventoryProduct(ctx context.Context, in *ManageInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error)
	CorrectInventoryStock(ctx context.Context, in *ManageInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error)
	ListStockMovements(ctx context.Context, in *ListStockMovementsRequest, opts ...grpc.CallOption) (*ListStockMovementsResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) PurchaseInventoryProduct(ctx context.Context, in *PurchaseInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, InventoryService_PurchaseInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) SupplyInventoryProduct(ctx context.Context, in *ManageInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, InventoryService_SupplyInventoryProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CorrectInventoryStock(ctx context.Context, in *ManageInventoryRequest, opts ...grpc.CallOption) (*StockMovement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockMovement)
	err := c.cc.Invoke(ctx, InventoryService_CorrectInventoryStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListStockMovements(ctx context.Context, in *ListStockMovementsRequest, opts ...grpc.CallOption) (*ListStockMovementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStockMovementsResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListStockMovements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	PurchaseInventoryProduct(context.Context, *PurchaseInventoryRequest) (*StockMovement, error)
	SupplyInventoryProduct(context.Context, *ManageInventoryRequest) (*StockMovement, error)
	CorrectInventoryStock(context.Context, *ManageInventoryRequest) (*StockMovement, error)
	ListStockMovements(context.Context, *ListStockMovementsRequest) (*ListStockMovementsResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) PurchaseInventoryProduct(context.Context, *PurchaseInventoryRequest) (*StockMovement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) SupplyInventoryProduct(context.Context, *ManageInventoryRequest) (*StockMovement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyInventoryProduct not implemented")
}
func (UnimplementedInventoryServiceServer) CorrectInventoryStock(context.Context, *ManageInventoryRequest) (*StockMovement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CorrectInventoryStock not implemented")
}
func (UnimplementedInventoryServiceServer) ListStockMovements(context.Context, *ListStockMovementsRequest) (*ListStockMovementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStockMovements not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_PurchaseInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).PurchaseInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_PurchaseInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).PurchaseInventoryProduct(ctx, req.(*PurchaseInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_SupplyInventoryProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).SupplyInventoryProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_SupplyInventoryProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).SupplyInventoryProduct(ctx, req.(*ManageInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CorrectInventoryStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CorrectInventoryStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CorrectInventoryStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CorrectInventoryStock(ctx, req.(*ManageInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListStockMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStockMovementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListStockMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListStockMovements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListStockMovements(ctx, req.(*ListStockMovementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchaseInventoryProduct",
			Handler:    _InventoryService_PurchaseInventoryProduct_Handler,
		},
		{
			MethodName: "SupplyInventoryProduct",
			Handler:    _InventoryService_SupplyInventoryProduct_Handler,
		},
		{
			MethodName: "CorrectInventoryStock",
			Handler:    _InventoryService_CorrectInventoryStock_Handler,
		},
		{
			MethodName: "ListStockMovements",
			Handler:    _InventoryService_ListStockMovements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
