// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: orders.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Items            []*OrderItem           `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	PaymentReference string                 `protobuf:"bytes,2,opt,name=PaymentReference,proto3" json:"PaymentReference,omitempty"`
	CustomerName     string                 `protobuf:"bytes,3,opt,name=CustomerName,proto3" json:"CustomerName,omitempty"`
	CustomerContact  string                 `protobuf:"bytes,4,opt,name=CustomerContact,proto3" json:"CustomerContact,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetPaymentReference() string {
	if x != nil {
		return x.PaymentReference
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomerContact() string {
	if x != nil {
		return x.CustomerContact
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=ProductId,proto3" json:"ProductId,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Order struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CustomerName     string                 `protobuf:"bytes,2,opt,name=CustomerName,proto3" json:"CustomerName,omitempty"`
	CustomerContact  string                 `protobuf:"bytes,3,opt,name=CustomerContact,proto3" json:"CustomerContact,omitempty"`
	PaymentReference string                 `protobuf:"bytes,4,opt,name=PaymentReference,proto3" json:"PaymentReference,omitempty"`
	Items            []*OrderItem           `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Order) GetCustomerContact() string {
	if x != nil {
		return x.CustomerContact
	}
	return ""
}

func (x *Order) GetPaymentReference() string {
	if x != nil {
		return x.PaymentReference
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type OrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIdRequest) Reset() {
	*x = OrderIdRequest{}
	mi := &file_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIdRequest) ProtoMessage() {}

func (x *OrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIdRequest.ProtoReflect.Descriptor instead.
func (*OrderIdRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{3}
}

func (x *OrderIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`      // Optional filter by status
	Page          int64                  `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`         // Optional limit for pagination
	PageSize      int64                  `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"` // Optional offset for pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOrdersRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=Orders,proto3" json:"Orders,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"` // Total number of orders matching the criteria
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{6}
}

type ChangeOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"` // New status for the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeOrderStatusRequest) Reset() {
	*x = ChangeOrderStatusRequest{}
	mi := &file_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeOrderStatusRequest) ProtoMessage() {}

func (x *ChangeOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeOrderStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\"\xb0\x01\n" +
	"\x12CreateOrderRequest\x12 \n" +
	"\x05Items\x18\x01 \x03(\v2\n" +
	".OrderItemR\x05Items\x12*\n" +
	"\x10PaymentReference\x18\x02 \x01(\tR\x10PaymentReference\x12\"\n" +
	"\fCustomerName\x18\x03 \x01(\tR\fCustomerName\x12(\n" +
	"\x0fCustomerContact\x18\x04 \x01(\tR\x0fCustomerContact\"E\n" +
	"\tOrderItem\x12\x1c\n" +
	"\tProductId\x18\x01 \x01(\x03R\tProductId\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x03R\bQuantity\"\xe9\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\"\n" +
	"\fCustomerName\x18\x02 \x01(\tR\fCustomerName\x12(\n" +
	"\x0fCustomerContact\x18\x03 \x01(\tR\x0fCustomerContact\x12*\n" +
	"\x10PaymentReference\x18\x04 \x01(\tR\x10PaymentReference\x12 \n" +
	"\x05Items\x18\x05 \x03(\v2\n" +
	".OrderItemR\x05Items\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\tR\x06Status\x12\x1c\n" +
	"\tCreatedAt\x18\a \x01(\tR\tCreatedAt\" \n" +
	"\x0eOrderIdRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"[\n" +
	"\x11ListOrdersRequest\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12\x12\n" +
	"\x04Page\x18\x03 \x01(\x03R\x04Page\x12\x1a\n" +
	"\bPageSize\x18\x04 \x01(\x03R\bPageSize\"T\n" +
	"\x12ListOrdersResponse\x12\x1e\n" +
	"\x06Orders\x18\x01 \x03(\v2\x06.OrderR\x06Orders\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x02 \x01(\x03R\n" +
	"TotalCount\"\x15\n" +
	"\x13DeleteOrderResponse\"B\n" +
	"\x18ChangeOrderStatusRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status2\x85\x02\n" +
	"\rOrdersService\x12*\n" +
	"\vCreateOrder\x12\x13.CreateOrderRequest\x1a\x06.Order\x12#\n" +
	"\bGetOrder\x12\x0f.OrderIdRequest\x1a\x06.Order\x125\n" +
	"\n" +
	"ListOrders\x12\x12.ListOrdersRequest\x1a\x13.ListOrdersResponse\x124\n" +
	"\vDeleteOrder\x12\x0f.OrderIdRequest\x1a\x14.DeleteOrderResponse\x126\n" +
	"\x11ChangeOrderStatus\x12\x19.ChangeOrderStatusRequest\x1a\x06.OrderB3Z1github.com/logan2k02/ims/shared/protobuf;protobufb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_orders_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),       // 0: CreateOrderRequest
	(*OrderItem)(nil),                // 1: OrderItem
	(*Order)(nil),                    // 2: Order
	(*OrderIdRequest)(nil),           // 3: OrderIdRequest
	(*ListOrdersRequest)(nil),        // 4: ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 5: ListOrdersResponse
	(*DeleteOrderResponse)(nil),      // 6: DeleteOrderResponse
	(*ChangeOrderStatusRequest)(nil), // 7: ChangeOrderStatusRequest
}
var file_orders_proto_depIdxs = []int32{
	1, // 0: CreateOrderRequest.Items:type_name -> OrderItem
	1, // 1: Order.Items:type_name -> OrderItem
	2, // 2: ListOrdersResponse.Orders:type_name -> Order
	0, // 3: OrdersService.CreateOrder:input_type -> CreateOrderRequest
	3, // 4: OrdersService.GetOrder:input_type -> OrderIdRequest
	4, // 5: OrdersService.ListOrders:input_type -> ListOrdersRequest
	3, // 6: OrdersService.DeleteOrder:input_type -> OrderIdRequest
	7, // 7: OrdersService.ChangeOrderStatus:input_type -> ChangeOrderStatusRequest
	2, // 8: OrdersService.CreateOrder:output_type -> Order
	2, // 9: OrdersService.GetOrder:output_type -> Order
	5, // 10: OrdersService.ListOrders:output_type -> ListOrdersResponse
	6, // 11: OrdersService.DeleteOrder:output_type -> DeleteOrderResponse
	2, // 12: OrdersService.ChangeOrderStatus:output_type -> Order
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
