package main

import (
	"context"

	"github.com/theshawa/imms/shared/protobuf"
)

type productsService struct {
	store *productsStore
}

func NewProductsService(store *productsStore) *productsService {
	return &productsService{store}
}

func (s *productsService) CreateProduct(ctx context.Context, payload *protobuf.CreateProductRequest) (*protobuf.Product, error) {
	return &protobuf.Product{
		Id:          "generated-id", // In a real application, this would be generated by
		Name:        payload.Name,
		Description: payload.Description,
		Price:       payload.Price,
	}, nil // In a real application, you would handle errors appropriately
}
